apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-deployment
        image: docker.io/lordagam/project-devops:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always  
        ports:
        - containerPort: 3000
        readinessProbe:  
          httpGet:
            path: /
            port: 3000
        livenessProbe:  
          httpGet:
            path: /
            port: 3000
