apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
spec:
  containers:
    - name: react-app
      image: lordagam/project-devops:frontend
      image: lordagam/project-devops:backend
      image: lordagam/project-devops:mariadb
      imagePullPolicy: Always
      ports:
        - containerPort: 80
        - containerPort: 3000
