apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
spec:
containers:
  - name: frontend
    image: lordagam/project-devops:frontend
    imagePullPolicy: Always
    ports:
      - containerPort: 80
  - name: backend
    image: lordagam/project-devops:backend
    imagePullPolicy: Always
    ports:
      - containerPort: 3000
  - name: mariadb
    image: lordagam/project-devops:mariadb
    imagePullPolicy: Always
    ports: 
      - containerPort: 8080
