apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: tomeroz802@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: argocd-secret
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
