apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  project: default
  source: 
    path: promtail
    repoURL: "https://github.com/lordagam/Tomer-Joseph_project-test.git" 
    targetRevision: main