apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
spec:
  destination:
    namespace: react
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  project: default
  source: 
    path: react-app-deployment
    repoURL: "https://github.com/lordagam/Tomer-Joseph_project-test.git" 
    targetRevision: main