name: CI-CD-Project-DevOps
on: 
  schedule:
   - cron: '0 0 * * *'
  push:
  
jobs:
 CI-Build-Test-Push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: cd react-app && ls && docker-compose up --build -d 
      
      - name: Run curl Test
        run: |
          sudo apt-get update; sudo apt-get install -y curl && curl http://localhost:3000 && docker ps && pwd
          
      - name: change image name
        run: |
          cd /home/runner/work/Project-DevOps-devops-prod.online/ && docker tag mariadb:10.6.4-focal lordagam/project-devops:mariadb && docker tag react-app_frontend lordagam/project-devops:frontend && docker tag react-app_backend lordagam/project-devops:backend
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: docker push
        run: docker push lordagam/project-devops:mariadb && docker push lordagam/project-devops:backend && docker push lordagam/project-devops:frontend
   
      - uses: actions/checkout@master
      - name: Slack Notification 
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
         SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
         SLACK_MESSAGE: 'DevOps pipeline''CI project successfully completed '
         SLACK_TITLE: 'CI project successfully completed '



 Snyk-security:
    needs: CI-Build-Test-Push
    runs-on: ubuntu-latest
    steps:          
      - name: Snyk Infrastructure as Code scan
        id: snyk-iac-scan
        uses: Gershon-A/snyk-iac-code-security-checks@v1.0.1
        continue-on-error: true
        with:
          SNYK_TOKEN: ${{ secrets.SNYKTOKEN }}
          SEVERITY_THRESHOLD: "critical"
          FILE: "example-*"
          update_pr_with_scan_results: true
   
 CD-Terraform:
   # needs: Snyk-security
    runs-on: self-hosted    
    defaults:
      run:
        shell: bash
    steps:
    - name: pwd
      run: pwd 

    - name: pull the Repo 
      run: git pull https://github.com/lordagam/Project-DevOps-devops-prod.online.git && ls -alh

    - name: Go To Dir-File 
      run: cd /home/ec2-user/Project-DevOps-devops-prod.online-actions-runner/_work/Project-DevOps-devops-prod.online/Terraform
    
    - name: Terraform Init
      run: cd .. && cd Terraform && ls -alh && terraform init

    - name: Terraform Validate
      run: cd .. && cd Terraform && ls -alh && terraform validate

    - name: Terraform Plan
      run: cd .. && cd Terraform && ls -alh && terraform plan
      
    - name: Terraform Apply
      run: cd .. && cd Terraform && ls -alh && terraform apply -auto-approve
    
    - name: output cluster name
      run: cd .. && cd Terraform && ls -alh && cat terraform.tfstate.backup | grep -A2 'cluster_name' | grep 'value' | awk -F'"' '{print $4}'
    
    - name: aws eks kubeconfig 
      run: cd .. && cd Terraform && ls -alh && aws eks --region sa-east-1 update-kubeconfig --name $(cat terraform.tfstate.backup | grep -A2 'cluster_name' | grep 'value' | awk -F'"' '{print $4}')
      
    - name: delete cert-manager
      run: kubectl delete namespace cert-manager || true

    - name: namespace-cert-manager
      run: kubectl create namespace cert-manager 
    
    - name: delete ingress-nginx
      run: kubectl delete namespace ingress-nginx || true

    - name: namespace-ingress-nginx
      run: kubectl create namespace ingress-nginx 
  
    - name: delete react
      run: kubectl delete namespace react  || true

    - name: namespace-react
      run: kubectl create namespace react

    - name: delete namespace-argocd
      run: kubectl delete namespace argocd  || true
      
    - name: delete monitoring
      run: kubectl delete namespace monitoring  || true

    - name: namespace-monitoring
      run: kubectl create namespace monitoring  
    
    - name: namespace-argocd
      run: kubectl create namespace argocd    
    
    
    - name: install_Ingress
      run: kubectl apply -n ingress-nginx  -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/aws/deploy.yaml

      
    - name: install_cert_manager
      run: cd .. && cd letsencrypt && ls -alh && chmod +x ./install_cert_manager.sh && ./install_cert_manager.sh
        
    - name: install argo-cd
      run: cd .. && cd letsencrypt && cd Argocd && ls -alh && kubectl apply -n argocd -f install.yaml && sleep 30

    - name: Pass argocd
      run: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d


    - name: apply argo-ingress
      run: cd .. && cd letsencrypt && cd Argocd && ls -alh && kubectl apply -f argo-ingress.yaml
  
    - name:  get ingress ns argocd
      run: kubectl get ingress -n argocd
    
    - name: install issue-prod-argocd
      run: cd .. && cd letsencrypt && cd Argocd && ls -alh  && kubectl apply -f issue-prod-argocd.yaml
    
    
    - name: show certificate
      run: kubectl get certificate -A
        
    - name: show Node
      run: kubectl get node
    
    - name: show Pods
      run: kubectl get pods -A

    - name: show svc
      run: kubectl get svc -A

    
    - name: Deploy React-App
      run: cd .. && cd react-app && cd deployment && cd argocd && ls -alh  && kubectl apply -f react-app-argo-deploy.yaml

    - name: Deploy Grafana
      run: cd .. && cd monitoring && cd grafana-deployment && cd argocd && ls -alh  && kubectl apply -f grafana-argo-deploy.yaml
   
    - name: install issue-prod-argocd
      run: cd .. && cd monitoring && cd grafana-deployment && ls -alh  && kubectl apply -f issue-grafana-prod.yaml


    - name: Deploy prometheus
      run: cd .. && cd monitoring && cd prometheus-deployment && cd argocd && ls -alh  && kubectl apply -f prometheus-argo-deploy.yaml
   
      
    - name: Deploy Loki
      run: cd .. && cd monitoring && cd loki && cd argocd && ls -alh  && kubectl apply -f loki-argo-deploy.yaml



      

 slack-Notification:
   name: Slack Notification 
   needs: CD-Terraform
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@master
     - name: Slack Notification 
       uses: bryannice/gitactions-slack-notification@2.0.0
       env:
        SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
        SLACK_MESSAGE: 'DevOps pipeline''CI/CD project successfully completed '
        SLACK_TITLE: 'CI/CD project successfully completed '
